// https://registry.terraform.io/providers/hashicorp/awscc/1.92.0/docs/resources/ec2_vpc_endpoint
// generated from terraform resource schema

import { Construct } from 'constructs';
import * as cdktn from 'cdktn';

// Configuration

export interface Ec2VpcEndpointConfig extends cdktn.TerraformMetaArguments {
  /**
  * Describes the DNS options for an endpoint.
  *
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/awscc/1.92.0/docs/resources/ec2_vpc_endpoint#dns_options Ec2VpcEndpoint#dns_options}
  */
  readonly dnsOptions?: Ec2VpcEndpointDnsOptions;
  /**
  * The supported IP address types.
  *
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/awscc/1.92.0/docs/resources/ec2_vpc_endpoint#ip_address_type Ec2VpcEndpoint#ip_address_type}
  */
  readonly ipAddressType?: string;
  /**
  * An endpoint policy, which controls access to the service from the VPC. The default endpoint policy allows full access to the service. Endpoint policies are supported only for gateway and interface endpoints.
  *  For CloudFormation templates in YAML, you can provide the policy in JSON or YAML format. For example, if you have a JSON policy, you can convert it to YAML before including it in the YAML template, and CFNlong converts the policy to JSON format before calling the API actions for privatelink. Alternatively, you can include the JSON directly in the YAML, as shown in the following ``Properties`` section:
  *  ``Properties: VpcEndpointType: 'Interface' ServiceName: !Sub 'com.amazonaws.${AWS::Region}.logs' PolicyDocument: '{ "Version":"2012-10-17", "Statement": [{ "Effect":"Allow", "Principal":"*", "Action":["logs:Describe*","logs:Get*","logs:List*","logs:FilterLogEvents"], "Resource":"*" }] }'``
  *
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/awscc/1.92.0/docs/resources/ec2_vpc_endpoint#policy_document Ec2VpcEndpoint#policy_document}
  */
  readonly policyDocument?: string;
  /**
  * Indicate whether to associate a private hosted zone with the specified VPC. The private hosted zone contains a record set for the default public DNS name for the service for the Region (for example, ``kinesis.us-east-1.amazonaws.com``), which resolves to the private IP addresses of the endpoint network interfaces in the VPC. This enables you to make requests to the default public DNS name for the service instead of the public DNS names that are automatically generated by the VPC endpoint service.
  *  To use a private hosted zone, you must set the following VPC attributes to ``true``: ``enableDnsHostnames`` and ``enableDnsSupport``.
  *  This property is supported only for interface endpoints.
  *  Default: ``false``
  *
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/awscc/1.92.0/docs/resources/ec2_vpc_endpoint#private_dns_enabled Ec2VpcEndpoint#private_dns_enabled}
  */
  readonly privateDnsEnabled?: boolean | cdktn.IResolvable;
  /**
  * The Amazon Resource Name (ARN) of the resource configuration.
  *
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/awscc/1.92.0/docs/resources/ec2_vpc_endpoint#resource_configuration_arn Ec2VpcEndpoint#resource_configuration_arn}
  */
  readonly resourceConfigurationArn?: string;
  /**
  * The IDs of the route tables. Routing is supported only for gateway endpoints.
  *
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/awscc/1.92.0/docs/resources/ec2_vpc_endpoint#route_table_ids Ec2VpcEndpoint#route_table_ids}
  */
  readonly routeTableIds?: string[];
  /**
  * The IDs of the security groups to associate with the endpoint network interfaces. If this parameter is not specified, we use the default security group for the VPC. Security groups are supported only for interface endpoints.
  *
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/awscc/1.92.0/docs/resources/ec2_vpc_endpoint#security_group_ids Ec2VpcEndpoint#security_group_ids}
  */
  readonly securityGroupIds?: string[];
  /**
  * The name of the endpoint service.
  *
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/awscc/1.92.0/docs/resources/ec2_vpc_endpoint#service_name Ec2VpcEndpoint#service_name}
  */
  readonly serviceName?: string;
  /**
  * The Amazon Resource Name (ARN) of the service network.
  *
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/awscc/1.92.0/docs/resources/ec2_vpc_endpoint#service_network_arn Ec2VpcEndpoint#service_network_arn}
  */
  readonly serviceNetworkArn?: string;
  /**
  * Describes a Region.
  *
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/awscc/1.92.0/docs/resources/ec2_vpc_endpoint#service_region Ec2VpcEndpoint#service_region}
  */
  readonly serviceRegion?: string;
  /**
  * The IDs of the subnets in which to create endpoint network interfaces. You must specify this property for an interface endpoint or a Gateway Load Balancer endpoint. You can't specify this property for a gateway endpoint. For a Gateway Load Balancer endpoint, you can specify only one subnet.
  *
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/awscc/1.92.0/docs/resources/ec2_vpc_endpoint#subnet_ids Ec2VpcEndpoint#subnet_ids}
  */
  readonly subnetIds?: string[];
  /**
  * The tags to associate with the endpoint.
  *
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/awscc/1.92.0/docs/resources/ec2_vpc_endpoint#tags Ec2VpcEndpoint#tags}
  */
  readonly tags?: Ec2VpcEndpointTags[] | cdktn.IResolvable;
  /**
  * The type of endpoint.
  *  Default: Gateway
  *
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/awscc/1.92.0/docs/resources/ec2_vpc_endpoint#vpc_endpoint_type Ec2VpcEndpoint#vpc_endpoint_type}
  */
  readonly vpcEndpointType?: string;
  /**
  * The ID of the VPC.
  *
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/awscc/1.92.0/docs/resources/ec2_vpc_endpoint#vpc_id Ec2VpcEndpoint#vpc_id}
  */
  readonly vpcId: string;
}
export interface Ec2VpcEndpointDnsOptions {
  /**
  * The DNS records created for the endpoint.
  *
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/awscc/1.92.0/docs/resources/ec2_vpc_endpoint#dns_record_ip_type Ec2VpcEndpoint#dns_record_ip_type}
  */
  readonly dnsRecordIpType?: string;
  /**
  * Indicates whether to enable private DNS only for inbound endpoints. This option is available only for services that support both gateway and interface endpoints. It routes traffic that originates from the VPC to the gateway endpoint and traffic that originates from on-premises to the interface endpoint.
  *
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/awscc/1.92.0/docs/resources/ec2_vpc_endpoint#private_dns_only_for_inbound_resolver_endpoint Ec2VpcEndpoint#private_dns_only_for_inbound_resolver_endpoint}
  */
  readonly privateDnsOnlyForInboundResolverEndpoint?: string;
  /**
  * The preference for which private domains have a private hosted zone created for and associated with the specified VPC. Only supported when private DNS is enabled and when the VPC endpoint type is ServiceNetwork or Resource.
  *
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/awscc/1.92.0/docs/resources/ec2_vpc_endpoint#private_dns_preference Ec2VpcEndpoint#private_dns_preference}
  */
  readonly privateDnsPreference?: string;
  /**
  * Indicates which of the private domains to create private hosted zones for and associate with the specified VPC. Only supported when private DNS is enabled and the private DNS preference is ``VERIFIED_DOMAINS_AND_SPECIFIED_DOMAINS`` or ``SPECIFIED_DOMAINS_ONLY``.
  *
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/awscc/1.92.0/docs/resources/ec2_vpc_endpoint#private_dns_specified_domains Ec2VpcEndpoint#private_dns_specified_domains}
  */
  readonly privateDnsSpecifiedDomains?: string[];
}

export function ec2VpcEndpointDnsOptionsToTerraform(struct?: Ec2VpcEndpointDnsOptions | cdktn.IResolvable): any {
  if (!cdktn.canInspect(struct) || cdktn.Tokenization.isResolvable(struct)) { return struct; }
  if (cdktn.isComplexElement(struct)) {
    throw new Error("A complex element was used as configuration, this is not supported: https://cdktn.io/docs/concepts/resources#references");
  }
  return {
    dns_record_ip_type: cdktn.stringToTerraform(struct!.dnsRecordIpType),
    private_dns_only_for_inbound_resolver_endpoint: cdktn.stringToTerraform(struct!.privateDnsOnlyForInboundResolverEndpoint),
    private_dns_preference: cdktn.stringToTerraform(struct!.privateDnsPreference),
    private_dns_specified_domains: cdktn.listMapper(cdktn.stringToTerraform, false)(struct!.privateDnsSpecifiedDomains),
  }
}


export function ec2VpcEndpointDnsOptionsToHclTerraform(struct?: Ec2VpcEndpointDnsOptions | cdktn.IResolvable): any {
  if (!cdktn.canInspect(struct) || cdktn.Tokenization.isResolvable(struct)) { return struct; }
  if (cdktn.isComplexElement(struct)) {
    throw new Error("A complex element was used as configuration, this is not supported: https://cdktn.io/docs/concepts/resources#references");
  }
  const attrs = {
    dns_record_ip_type: {
      value: cdktn.stringToHclTerraform(struct!.dnsRecordIpType),
      isBlock: false,
      type: "simple",
      storageClassType: "string",
    },
    private_dns_only_for_inbound_resolver_endpoint: {
      value: cdktn.stringToHclTerraform(struct!.privateDnsOnlyForInboundResolverEndpoint),
      isBlock: false,
      type: "simple",
      storageClassType: "string",
    },
    private_dns_preference: {
      value: cdktn.stringToHclTerraform(struct!.privateDnsPreference),
      isBlock: false,
      type: "simple",
      storageClassType: "string",
    },
    private_dns_specified_domains: {
      value: cdktn.listMapperHcl(cdktn.stringToHclTerraform, false)(struct!.privateDnsSpecifiedDomains),
      isBlock: false,
      type: "list",
      storageClassType: "stringList",
    },
  };

  // remove undefined attributes
  return Object.fromEntries(Object.entries(attrs).filter(([_, value]) => value !== undefined && value.value !== undefined));
}

export class Ec2VpcEndpointDnsOptionsOutputReference extends cdktn.ComplexObject {
  private isEmptyObject = false;
  private resolvableValue?: cdktn.IResolvable;

  /**
  * @param terraformResource The parent resource
  * @param terraformAttribute The attribute on the parent resource this class is referencing
  */
  public constructor(terraformResource: cdktn.IInterpolatingParent, terraformAttribute: string) {
    super(terraformResource, terraformAttribute, false);
  }

  public get internalValue(): Ec2VpcEndpointDnsOptions | cdktn.IResolvable | undefined {
    if (this.resolvableValue) {
      return this.resolvableValue;
    }
    let hasAnyValues = this.isEmptyObject;
    const internalValueResult: any = {};
    if (this._dnsRecordIpType !== undefined) {
      hasAnyValues = true;
      internalValueResult.dnsRecordIpType = this._dnsRecordIpType;
    }
    if (this._privateDnsOnlyForInboundResolverEndpoint !== undefined) {
      hasAnyValues = true;
      internalValueResult.privateDnsOnlyForInboundResolverEndpoint = this._privateDnsOnlyForInboundResolverEndpoint;
    }
    if (this._privateDnsPreference !== undefined) {
      hasAnyValues = true;
      internalValueResult.privateDnsPreference = this._privateDnsPreference;
    }
    if (this._privateDnsSpecifiedDomains !== undefined) {
      hasAnyValues = true;
      internalValueResult.privateDnsSpecifiedDomains = this._privateDnsSpecifiedDomains;
    }
    return hasAnyValues ? internalValueResult : undefined;
  }

  public set internalValue(value: Ec2VpcEndpointDnsOptions | cdktn.IResolvable | undefined) {
    if (value === undefined) {
      this.isEmptyObject = false;
      this.resolvableValue = undefined;
      this._dnsRecordIpType = undefined;
      this._privateDnsOnlyForInboundResolverEndpoint = undefined;
      this._privateDnsPreference = undefined;
      this._privateDnsSpecifiedDomains = undefined;
    }
    else if (cdktn.Tokenization.isResolvable(value)) {
      this.isEmptyObject = false;
      this.resolvableValue = value;
    }
    else {
      this.isEmptyObject = Object.keys(value).length === 0;
      this.resolvableValue = undefined;
      this._dnsRecordIpType = value.dnsRecordIpType;
      this._privateDnsOnlyForInboundResolverEndpoint = value.privateDnsOnlyForInboundResolverEndpoint;
      this._privateDnsPreference = value.privateDnsPreference;
      this._privateDnsSpecifiedDomains = value.privateDnsSpecifiedDomains;
    }
  }

  // dns_record_ip_type - computed: true, optional: true, required: false
  private _dnsRecordIpType?: string; 
  public get dnsRecordIpType() {
    return this.getStringAttribute('dns_record_ip_type');
  }
  public set dnsRecordIpType(value: string) {
    this._dnsRecordIpType = value;
  }
  public resetDnsRecordIpType() {
    this._dnsRecordIpType = undefined;
  }
  // Temporarily expose input value. Use with caution.
  public get dnsRecordIpTypeInput() {
    return this._dnsRecordIpType;
  }

  // private_dns_only_for_inbound_resolver_endpoint - computed: true, optional: true, required: false
  private _privateDnsOnlyForInboundResolverEndpoint?: string; 
  public get privateDnsOnlyForInboundResolverEndpoint() {
    return this.getStringAttribute('private_dns_only_for_inbound_resolver_endpoint');
  }
  public set privateDnsOnlyForInboundResolverEndpoint(value: string) {
    this._privateDnsOnlyForInboundResolverEndpoint = value;
  }
  public resetPrivateDnsOnlyForInboundResolverEndpoint() {
    this._privateDnsOnlyForInboundResolverEndpoint = undefined;
  }
  // Temporarily expose input value. Use with caution.
  public get privateDnsOnlyForInboundResolverEndpointInput() {
    return this._privateDnsOnlyForInboundResolverEndpoint;
  }

  // private_dns_preference - computed: true, optional: true, required: false
  private _privateDnsPreference?: string; 
  public get privateDnsPreference() {
    return this.getStringAttribute('private_dns_preference');
  }
  public set privateDnsPreference(value: string) {
    this._privateDnsPreference = value;
  }
  public resetPrivateDnsPreference() {
    this._privateDnsPreference = undefined;
  }
  // Temporarily expose input value. Use with caution.
  public get privateDnsPreferenceInput() {
    return this._privateDnsPreference;
  }

  // private_dns_specified_domains - computed: true, optional: true, required: false
  private _privateDnsSpecifiedDomains?: string[]; 
  public get privateDnsSpecifiedDomains() {
    return this.getListAttribute('private_dns_specified_domains');
  }
  public set privateDnsSpecifiedDomains(value: string[]) {
    this._privateDnsSpecifiedDomains = value;
  }
  public resetPrivateDnsSpecifiedDomains() {
    this._privateDnsSpecifiedDomains = undefined;
  }
  // Temporarily expose input value. Use with caution.
  public get privateDnsSpecifiedDomainsInput() {
    return this._privateDnsSpecifiedDomains;
  }
}
export interface Ec2VpcEndpointTags {
  /**
  * The key of the tag.
  *  Constraints: Tag keys are case-sensitive and accept a maximum of 127 Unicode characters. May not begin with ``aws:``.
  *
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/awscc/1.92.0/docs/resources/ec2_vpc_endpoint#key Ec2VpcEndpoint#key}
  */
  readonly key?: string;
  /**
  * The value of the tag.
  *  Constraints: Tag values are case-sensitive and accept a maximum of 256 Unicode characters.
  *
  * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/awscc/1.92.0/docs/resources/ec2_vpc_endpoint#value Ec2VpcEndpoint#value}
  */
  readonly value?: string;
}

export function ec2VpcEndpointTagsToTerraform(struct?: Ec2VpcEndpointTags | cdktn.IResolvable): any {
  if (!cdktn.canInspect(struct) || cdktn.Tokenization.isResolvable(struct)) { return struct; }
  if (cdktn.isComplexElement(struct)) {
    throw new Error("A complex element was used as configuration, this is not supported: https://cdktn.io/docs/concepts/resources#references");
  }
  return {
    key: cdktn.stringToTerraform(struct!.key),
    value: cdktn.stringToTerraform(struct!.value),
  }
}


export function ec2VpcEndpointTagsToHclTerraform(struct?: Ec2VpcEndpointTags | cdktn.IResolvable): any {
  if (!cdktn.canInspect(struct) || cdktn.Tokenization.isResolvable(struct)) { return struct; }
  if (cdktn.isComplexElement(struct)) {
    throw new Error("A complex element was used as configuration, this is not supported: https://cdktn.io/docs/concepts/resources#references");
  }
  const attrs = {
    key: {
      value: cdktn.stringToHclTerraform(struct!.key),
      isBlock: false,
      type: "simple",
      storageClassType: "string",
    },
    value: {
      value: cdktn.stringToHclTerraform(struct!.value),
      isBlock: false,
      type: "simple",
      storageClassType: "string",
    },
  };

  // remove undefined attributes
  return Object.fromEntries(Object.entries(attrs).filter(([_, value]) => value !== undefined && value.value !== undefined));
}

export class Ec2VpcEndpointTagsOutputReference extends cdktn.ComplexObject {
  private isEmptyObject = false;
  private resolvableValue?: cdktn.IResolvable;

  /**
  * @param terraformResource The parent resource
  * @param terraformAttribute The attribute on the parent resource this class is referencing
  * @param complexObjectIndex the index of this item in the list
  * @param complexObjectIsFromSet whether the list is wrapping a set (will add tolist() to be able to access an item via an index)
  */
  public constructor(terraformResource: cdktn.IInterpolatingParent, terraformAttribute: string, complexObjectIndex: number, complexObjectIsFromSet: boolean) {
    super(terraformResource, terraformAttribute, complexObjectIsFromSet, complexObjectIndex);
  }

  public get internalValue(): Ec2VpcEndpointTags | cdktn.IResolvable | undefined {
    if (this.resolvableValue) {
      return this.resolvableValue;
    }
    let hasAnyValues = this.isEmptyObject;
    const internalValueResult: any = {};
    if (this._key !== undefined) {
      hasAnyValues = true;
      internalValueResult.key = this._key;
    }
    if (this._value !== undefined) {
      hasAnyValues = true;
      internalValueResult.value = this._value;
    }
    return hasAnyValues ? internalValueResult : undefined;
  }

  public set internalValue(value: Ec2VpcEndpointTags | cdktn.IResolvable | undefined) {
    if (value === undefined) {
      this.isEmptyObject = false;
      this.resolvableValue = undefined;
      this._key = undefined;
      this._value = undefined;
    }
    else if (cdktn.Tokenization.isResolvable(value)) {
      this.isEmptyObject = false;
      this.resolvableValue = value;
    }
    else {
      this.isEmptyObject = Object.keys(value).length === 0;
      this.resolvableValue = undefined;
      this._key = value.key;
      this._value = value.value;
    }
  }

  // key - computed: true, optional: true, required: false
  private _key?: string; 
  public get key() {
    return this.getStringAttribute('key');
  }
  public set key(value: string) {
    this._key = value;
  }
  public resetKey() {
    this._key = undefined;
  }
  // Temporarily expose input value. Use with caution.
  public get keyInput() {
    return this._key;
  }

  // value - computed: true, optional: true, required: false
  private _value?: string; 
  public get value() {
    return this.getStringAttribute('value');
  }
  public set value(value: string) {
    this._value = value;
  }
  public resetValue() {
    this._value = undefined;
  }
  // Temporarily expose input value. Use with caution.
  public get valueInput() {
    return this._value;
  }
}

export class Ec2VpcEndpointTagsList extends cdktn.ComplexList {
  public internalValue? : Ec2VpcEndpointTags[] | cdktn.IResolvable

  /**
  * @param terraformResource The parent resource
  * @param terraformAttribute The attribute on the parent resource this class is referencing
  * @param wrapsSet whether the list is wrapping a set (will add tolist() to be able to access an item via an index)
  */
  constructor(terraformResource: cdktn.IInterpolatingParent, terraformAttribute: string, wrapsSet: boolean) {
    super(terraformResource, terraformAttribute, wrapsSet);
  }

  /**
  * @param index the index of the item to return
  */
  public get(index: number): Ec2VpcEndpointTagsOutputReference {
    return new Ec2VpcEndpointTagsOutputReference(this.terraformResource, this.terraformAttribute, index, this.wrapsSet);
  }
}

/**
* Represents a {@link https://registry.terraform.io/providers/hashicorp/awscc/1.92.0/docs/resources/ec2_vpc_endpoint awscc_ec2_vpc_endpoint}
*/
export class Ec2VpcEndpoint extends cdktn.TerraformResource {

  // =================
  // STATIC PROPERTIES
  // =================
  public static readonly tfResourceType = "awscc_ec2_vpc_endpoint";

  // ==============
  // STATIC Methods
  // ==============
  /**
  * Generates CDKTN code for importing a Ec2VpcEndpoint resource upon running "cdktn plan <stack-name>"
  * @param scope The scope in which to define this construct
  * @param importToId The construct id used in the generated config for the Ec2VpcEndpoint to import
  * @param importFromId The id of the existing Ec2VpcEndpoint that should be imported. Refer to the {@link https://registry.terraform.io/providers/hashicorp/awscc/1.92.0/docs/resources/ec2_vpc_endpoint#import import section} in the documentation of this resource for the id to use
  * @param provider? Optional instance of the provider where the Ec2VpcEndpoint to import is found
  */
  public static generateConfigForImport(scope: Construct, importToId: string, importFromId: string, provider?: cdktn.TerraformProvider) {
        return new cdktn.ImportableResource(scope, importToId, { terraformResourceType: "awscc_ec2_vpc_endpoint", importId: importFromId, provider });
      }

  // ===========
  // INITIALIZER
  // ===========

  /**
  * Create a new {@link https://registry.terraform.io/providers/hashicorp/awscc/1.92.0/docs/resources/ec2_vpc_endpoint awscc_ec2_vpc_endpoint} Resource
  *
  * @param scope The scope in which to define this construct
  * @param id The scoped construct ID. Must be unique amongst siblings in the same scope
  * @param options Ec2VpcEndpointConfig
  */
  public constructor(scope: Construct, id: string, config: Ec2VpcEndpointConfig) {
    super(scope, id, {
      terraformResourceType: 'awscc_ec2_vpc_endpoint',
      terraformGeneratorMetadata: {
        providerName: 'awscc',
        providerVersion: '1.92.0'
      },
      provider: config.provider,
      dependsOn: config.dependsOn,
      count: config.count,
      lifecycle: config.lifecycle,
      provisioners: config.provisioners,
      connection: config.connection,
      forEach: config.forEach
    });
    this._dnsOptions.internalValue = config.dnsOptions;
    this._ipAddressType = config.ipAddressType;
    this._policyDocument = config.policyDocument;
    this._privateDnsEnabled = config.privateDnsEnabled;
    this._resourceConfigurationArn = config.resourceConfigurationArn;
    this._routeTableIds = config.routeTableIds;
    this._securityGroupIds = config.securityGroupIds;
    this._serviceName = config.serviceName;
    this._serviceNetworkArn = config.serviceNetworkArn;
    this._serviceRegion = config.serviceRegion;
    this._subnetIds = config.subnetIds;
    this._tags.internalValue = config.tags;
    this._vpcEndpointType = config.vpcEndpointType;
    this._vpcId = config.vpcId;
  }

  // ==========
  // ATTRIBUTES
  // ==========

  // creation_timestamp - computed: true, optional: false, required: false
  public get creationTimestamp() {
    return this.getStringAttribute('creation_timestamp');
  }

  // dns_entries - computed: true, optional: false, required: false
  public get dnsEntries() {
    return this.getListAttribute('dns_entries');
  }

  // dns_options - computed: true, optional: true, required: false
  private _dnsOptions = new Ec2VpcEndpointDnsOptionsOutputReference(this, "dns_options");
  public get dnsOptions() {
    return this._dnsOptions;
  }
  public putDnsOptions(value: Ec2VpcEndpointDnsOptions) {
    this._dnsOptions.internalValue = value;
  }
  public resetDnsOptions() {
    this._dnsOptions.internalValue = undefined;
  }
  // Temporarily expose input value. Use with caution.
  public get dnsOptionsInput() {
    return this._dnsOptions.internalValue;
  }

  // id - computed: true, optional: false, required: false
  public get id() {
    return this.getStringAttribute('id');
  }

  // ip_address_type - computed: true, optional: true, required: false
  private _ipAddressType?: string; 
  public get ipAddressType() {
    return this.getStringAttribute('ip_address_type');
  }
  public set ipAddressType(value: string) {
    this._ipAddressType = value;
  }
  public resetIpAddressType() {
    this._ipAddressType = undefined;
  }
  // Temporarily expose input value. Use with caution.
  public get ipAddressTypeInput() {
    return this._ipAddressType;
  }

  // network_interface_ids - computed: true, optional: false, required: false
  public get networkInterfaceIds() {
    return this.getListAttribute('network_interface_ids');
  }

  // policy_document - computed: true, optional: true, required: false
  private _policyDocument?: string; 
  public get policyDocument() {
    return this.getStringAttribute('policy_document');
  }
  public set policyDocument(value: string) {
    this._policyDocument = value;
  }
  public resetPolicyDocument() {
    this._policyDocument = undefined;
  }
  // Temporarily expose input value. Use with caution.
  public get policyDocumentInput() {
    return this._policyDocument;
  }

  // private_dns_enabled - computed: true, optional: true, required: false
  private _privateDnsEnabled?: boolean | cdktn.IResolvable; 
  public get privateDnsEnabled() {
    return this.getBooleanAttribute('private_dns_enabled');
  }
  public set privateDnsEnabled(value: boolean | cdktn.IResolvable) {
    this._privateDnsEnabled = value;
  }
  public resetPrivateDnsEnabled() {
    this._privateDnsEnabled = undefined;
  }
  // Temporarily expose input value. Use with caution.
  public get privateDnsEnabledInput() {
    return this._privateDnsEnabled;
  }

  // resource_configuration_arn - computed: true, optional: true, required: false
  private _resourceConfigurationArn?: string; 
  public get resourceConfigurationArn() {
    return this.getStringAttribute('resource_configuration_arn');
  }
  public set resourceConfigurationArn(value: string) {
    this._resourceConfigurationArn = value;
  }
  public resetResourceConfigurationArn() {
    this._resourceConfigurationArn = undefined;
  }
  // Temporarily expose input value. Use with caution.
  public get resourceConfigurationArnInput() {
    return this._resourceConfigurationArn;
  }

  // route_table_ids - computed: true, optional: true, required: false
  private _routeTableIds?: string[]; 
  public get routeTableIds() {
    return cdktn.Fn.tolist(this.getListAttribute('route_table_ids'));
  }
  public set routeTableIds(value: string[]) {
    this._routeTableIds = value;
  }
  public resetRouteTableIds() {
    this._routeTableIds = undefined;
  }
  // Temporarily expose input value. Use with caution.
  public get routeTableIdsInput() {
    return this._routeTableIds;
  }

  // security_group_ids - computed: true, optional: true, required: false
  private _securityGroupIds?: string[]; 
  public get securityGroupIds() {
    return cdktn.Fn.tolist(this.getListAttribute('security_group_ids'));
  }
  public set securityGroupIds(value: string[]) {
    this._securityGroupIds = value;
  }
  public resetSecurityGroupIds() {
    this._securityGroupIds = undefined;
  }
  // Temporarily expose input value. Use with caution.
  public get securityGroupIdsInput() {
    return this._securityGroupIds;
  }

  // service_name - computed: true, optional: true, required: false
  private _serviceName?: string; 
  public get serviceName() {
    return this.getStringAttribute('service_name');
  }
  public set serviceName(value: string) {
    this._serviceName = value;
  }
  public resetServiceName() {
    this._serviceName = undefined;
  }
  // Temporarily expose input value. Use with caution.
  public get serviceNameInput() {
    return this._serviceName;
  }

  // service_network_arn - computed: true, optional: true, required: false
  private _serviceNetworkArn?: string; 
  public get serviceNetworkArn() {
    return this.getStringAttribute('service_network_arn');
  }
  public set serviceNetworkArn(value: string) {
    this._serviceNetworkArn = value;
  }
  public resetServiceNetworkArn() {
    this._serviceNetworkArn = undefined;
  }
  // Temporarily expose input value. Use with caution.
  public get serviceNetworkArnInput() {
    return this._serviceNetworkArn;
  }

  // service_region - computed: true, optional: true, required: false
  private _serviceRegion?: string; 
  public get serviceRegion() {
    return this.getStringAttribute('service_region');
  }
  public set serviceRegion(value: string) {
    this._serviceRegion = value;
  }
  public resetServiceRegion() {
    this._serviceRegion = undefined;
  }
  // Temporarily expose input value. Use with caution.
  public get serviceRegionInput() {
    return this._serviceRegion;
  }

  // subnet_ids - computed: true, optional: true, required: false
  private _subnetIds?: string[]; 
  public get subnetIds() {
    return cdktn.Fn.tolist(this.getListAttribute('subnet_ids'));
  }
  public set subnetIds(value: string[]) {
    this._subnetIds = value;
  }
  public resetSubnetIds() {
    this._subnetIds = undefined;
  }
  // Temporarily expose input value. Use with caution.
  public get subnetIdsInput() {
    return this._subnetIds;
  }

  // tags - computed: true, optional: true, required: false
  private _tags = new Ec2VpcEndpointTagsList(this, "tags", false);
  public get tags() {
    return this._tags;
  }
  public putTags(value: Ec2VpcEndpointTags[] | cdktn.IResolvable) {
    this._tags.internalValue = value;
  }
  public resetTags() {
    this._tags.internalValue = undefined;
  }
  // Temporarily expose input value. Use with caution.
  public get tagsInput() {
    return this._tags.internalValue;
  }

  // vpc_endpoint_id - computed: true, optional: false, required: false
  public get vpcEndpointId() {
    return this.getStringAttribute('vpc_endpoint_id');
  }

  // vpc_endpoint_type - computed: true, optional: true, required: false
  private _vpcEndpointType?: string; 
  public get vpcEndpointType() {
    return this.getStringAttribute('vpc_endpoint_type');
  }
  public set vpcEndpointType(value: string) {
    this._vpcEndpointType = value;
  }
  public resetVpcEndpointType() {
    this._vpcEndpointType = undefined;
  }
  // Temporarily expose input value. Use with caution.
  public get vpcEndpointTypeInput() {
    return this._vpcEndpointType;
  }

  // vpc_id - computed: false, optional: false, required: true
  private _vpcId?: string; 
  public get vpcId() {
    return this.getStringAttribute('vpc_id');
  }
  public set vpcId(value: string) {
    this._vpcId = value;
  }
  // Temporarily expose input value. Use with caution.
  public get vpcIdInput() {
    return this._vpcId;
  }

  // =========
  // SYNTHESIS
  // =========

  protected synthesizeAttributes(): { [name: string]: any } {
    return {
      dns_options: ec2VpcEndpointDnsOptionsToTerraform(this._dnsOptions.internalValue),
      ip_address_type: cdktn.stringToTerraform(this._ipAddressType),
      policy_document: cdktn.stringToTerraform(this._policyDocument),
      private_dns_enabled: cdktn.booleanToTerraform(this._privateDnsEnabled),
      resource_configuration_arn: cdktn.stringToTerraform(this._resourceConfigurationArn),
      route_table_ids: cdktn.listMapper(cdktn.stringToTerraform, false)(this._routeTableIds),
      security_group_ids: cdktn.listMapper(cdktn.stringToTerraform, false)(this._securityGroupIds),
      service_name: cdktn.stringToTerraform(this._serviceName),
      service_network_arn: cdktn.stringToTerraform(this._serviceNetworkArn),
      service_region: cdktn.stringToTerraform(this._serviceRegion),
      subnet_ids: cdktn.listMapper(cdktn.stringToTerraform, false)(this._subnetIds),
      tags: cdktn.listMapper(ec2VpcEndpointTagsToTerraform, false)(this._tags.internalValue),
      vpc_endpoint_type: cdktn.stringToTerraform(this._vpcEndpointType),
      vpc_id: cdktn.stringToTerraform(this._vpcId),
    };
  }

  protected synthesizeHclAttributes(): { [name: string]: any } {
    const attrs = {
      dns_options: {
        value: ec2VpcEndpointDnsOptionsToHclTerraform(this._dnsOptions.internalValue),
        isBlock: true,
        type: "struct",
        storageClassType: "Ec2VpcEndpointDnsOptions",
      },
      ip_address_type: {
        value: cdktn.stringToHclTerraform(this._ipAddressType),
        isBlock: false,
        type: "simple",
        storageClassType: "string",
      },
      policy_document: {
        value: cdktn.stringToHclTerraform(this._policyDocument),
        isBlock: false,
        type: "simple",
        storageClassType: "string",
      },
      private_dns_enabled: {
        value: cdktn.booleanToHclTerraform(this._privateDnsEnabled),
        isBlock: false,
        type: "simple",
        storageClassType: "boolean",
      },
      resource_configuration_arn: {
        value: cdktn.stringToHclTerraform(this._resourceConfigurationArn),
        isBlock: false,
        type: "simple",
        storageClassType: "string",
      },
      route_table_ids: {
        value: cdktn.listMapperHcl(cdktn.stringToHclTerraform, false)(this._routeTableIds),
        isBlock: false,
        type: "set",
        storageClassType: "stringList",
      },
      security_group_ids: {
        value: cdktn.listMapperHcl(cdktn.stringToHclTerraform, false)(this._securityGroupIds),
        isBlock: false,
        type: "set",
        storageClassType: "stringList",
      },
      service_name: {
        value: cdktn.stringToHclTerraform(this._serviceName),
        isBlock: false,
        type: "simple",
        storageClassType: "string",
      },
      service_network_arn: {
        value: cdktn.stringToHclTerraform(this._serviceNetworkArn),
        isBlock: false,
        type: "simple",
        storageClassType: "string",
      },
      service_region: {
        value: cdktn.stringToHclTerraform(this._serviceRegion),
        isBlock: false,
        type: "simple",
        storageClassType: "string",
      },
      subnet_ids: {
        value: cdktn.listMapperHcl(cdktn.stringToHclTerraform, false)(this._subnetIds),
        isBlock: false,
        type: "set",
        storageClassType: "stringList",
      },
      tags: {
        value: cdktn.listMapperHcl(ec2VpcEndpointTagsToHclTerraform, false)(this._tags.internalValue),
        isBlock: true,
        type: "list",
        storageClassType: "Ec2VpcEndpointTagsList",
      },
      vpc_endpoint_type: {
        value: cdktn.stringToHclTerraform(this._vpcEndpointType),
        isBlock: false,
        type: "simple",
        storageClassType: "string",
      },
      vpc_id: {
        value: cdktn.stringToHclTerraform(this._vpcId),
        isBlock: false,
        type: "simple",
        storageClassType: "string",
      },
    };

    // remove undefined attributes
    return Object.fromEntries(Object.entries(attrs).filter(([_, value]) => value !== undefined && value.value !== undefined ))
  }
}
